calories-calculator:
  products:
    - name: "Филе куриной грудки"
      protein: 20
      fats: 2
      carbohydrates: 0
    - name: "Филе бедра"
      protein: 18
      fats: 8
      carbohydrates: 0
    - name: "филе минтая"
      protein: 20
      fats: 1
      carbohydrates: 0
    - name: "зелень"
      protein: 3
      fats: 0.4
      carbohydrates: 7.6
    - name: "чеснок"
      protein: 6.4
      fats: 0.5
      carbohydrates: 33.1
    - name: "Салат листовой"
      protein: 1.5
      fats: 0.2
      carbohydrates: 3.12
    - name: "Салат Айсберг"
      protein: 0.9
      fats: 0.1
      carbohydrates: 1.8
    - name: "Помидоры"
      protein: 0.9
      fats: 0.2
      carbohydrates: 3.9
    - name: "Огурцы"
      protein: 0.8
      fats: 0.1
      carbohydrates: 2.8
    - name: "Лук репчатый"
      protein: 1.4
      fats: 0.2
      carbohydrates: 8.2
    - name: "Лук зеленый"
      protein: 1
      fats: 0.5
      carbohydrates: 5.7
    - name: "Болгарский перец"
      protein: 1.3
      fats: 0.1
      carbohydrates: 5.3
    - name: "Яйцо"
      protein: 12.7
      fats: 11.5
      carbohydrates: 0.7
    - name: "йогурт греческий"
      protein: 8.7
      fats: 2
      carbohydrates: 2.8
    - name: "Масло растительное"
      protein: 0
      fats: 100
      carbohydrates: 0
    - name: "Соевый соус"
      protein: 2.5
      fats: 0
      carbohydrates: 11
    - name: "устричный соус"
      protein: 5.1
      fats: 0
      carbohydrates: 28
    - name: "Горчица французская"
      protein: 7.5
      fats: 8.6
      carbohydrates: 8.4
    - name: "Творог обезжиренный"
      protein: 18
      fats: 1.8
      carbohydrates: 3.3
    - name: "protein"
      protein: 90
      fats: 1
      carbohydrates: 3.7
    - name: "Сахар"
      protein: 0
      fats: 0
      carbohydrates: 99.9
    - name: "мука цельнозерновая"
      protein: 11.3
      fats: 2.1
      carbohydrates: 65.4
    - name: "мука полбяная"
      protein: 14.57
      fats: 2.43
      carbohydrates: 70.19
    - name: "мука в/с"
      protein: 12
      fats: 1
      carbohydrates: 75